apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tungsten-analytics-snmp
  namespace: {{ .TF_NAMESPACE }}
  labels:
    app: tungsten-analytics-snmp
spec:
  selector:
    matchLabels:
      app: tungsten-analytics-snmp
  template:
    metadata:
      labels:
        app: tungsten-analytics-snmp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.tungsten.io/analytics_snmp"
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      shareProcessNamespace: true
      initContainers:
      - name: tungsten-node-init
        image: "{{ .CONTAINER_REGISTRY }}/{{ .CONTAINER_PREFIX }}-node-init:{{ .CONTAINER_TAG }}"
        imagePullPolicy: ""
        env:
        - name: NODE_TYPE
          value: "analytics-snmp"
        - name: CONTRAIL_STATUS_IMAGE
          value: "{{ .CONTAINER_REGISTRY }}/{{ .CONTAINER_PREFIX }}-status:{{ .CONTAINER_TAG }}"
        envFrom:
        - configMapRef:
            name: env
        - configMapRef:
            name: tungsten-analyticsdb-config
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host/usr/bin
          name: host-usr-bin
        - mountPath: /host/var/lib
          name: host-var-lib
      containers:
      - name: tungsten-analytics-snmp-collector
        image: "{{ .CONTAINER_REGISTRY }}/{{ .CONTAINER_PREFIX }}-analytics-snmp-collector:{{ .CONTAINER_TAG }}"
        imagePullPolicy: ""
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: env
        volumeMounts:
        - mountPath: /var/log/contrail
          name: analytics-snmp-logs
        env:
        - name: NODE_TYPE
          value: analytics-snmp
      - name: tungsten-analytics-snmp-topology
        image: "{{ .CONTAINER_REGISTRY }}/{{ .CONTAINER_PREFIX }}-analytics-snmp-topology:{{ .CONTAINER_TAG }}"
        imagePullPolicy: ""
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: env
        volumeMounts:
        - mountPath: /var/log/contrail
          name: analytics-snmp-logs
        env:
        - name: NODE_TYPE
          value: analytics-snmp
      - name: tungsten-analytics-snmp-nodemgr
        image: "{{ .CONTAINER_REGISTRY }}/{{ .CONTAINER_PREFIX }}-nodemgr:{{ .CONTAINER_TAG }}"
        imagePullPolicy: ""
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: env
        - configMapRef:
            name: nodemgr-config
        - configMapRef:
            name: tungsten-analyticsdb-config
        env:
        - name: NODE_TYPE
          value: analytics-snmp
        volumeMounts:
        - mountPath: /var/log/contrail
          name: analytics-snmp-logs
        - mountPath: /mnt
          name: docker-unix-socket
      - name: tungsten-analytics-snmp-provisioner
        image: "{{ .CONTAINER_REGISTRY }}/{{ .CONTAINER_PREFIX }}-provisioner:{{ .CONTAINER_TAG }}"
        imagePullPolicy: ""
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: env
        - configMapRef:
            name: defaults-env
        - configMapRef:
            name: nodemgr-config
        - configMapRef:
            name: tungsten-analyticsdb-config
        env:
        - name: NODE_TYPE
          value: analytics-snmp
        volumeMounts:
        - mountPath: /var/log/contrail
          name: analytics-snmp-logs
      imagePullSecrets:
      - name: {{ .TUNGSTEN_IMAGE_PULL_SECRET }}
      volumes:
      - name: analytics-snmp-logs
        hostPath:
          path: /var/log/contrail/analytics-snmp
      - name: host-var-lib
        hostPath:
          path: /var/lib
      - name: docker-unix-socket
        hostPath:
          path: /var/run
      - name: host-usr-bin
        hostPath:
          path: /opt/tungsten/bin
