// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpFabricNetworkType) DeepCopyInto(out *IpFabricNetworkType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpFabricNetworkType.
func (in *IpFabricNetworkType) DeepCopy() *IpFabricNetworkType {
	if in == nil {
		return nil
	}
	out := new(IpFabricNetworkType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodNetworkType) DeepCopyInto(out *PodNetworkType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodNetworkType.
func (in *PodNetworkType) DeepCopy() *PodNetworkType {
	if in == nil {
		return nil
	}
	out := new(PodNetworkType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNetworkType) DeepCopyInto(out *ServiceNetworkType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNetworkType.
func (in *ServiceNetworkType) DeepCopy() *ServiceNetworkType {
	if in == nil {
		return nil
	}
	out := new(ServiceNetworkType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TungstenCNI) DeepCopyInto(out *TungstenCNI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TungstenCNI.
func (in *TungstenCNI) DeepCopy() *TungstenCNI {
	if in == nil {
		return nil
	}
	out := new(TungstenCNI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TungstenCNI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TungstenCNIList) DeepCopyInto(out *TungstenCNIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TungstenCNI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TungstenCNIList.
func (in *TungstenCNIList) DeepCopy() *TungstenCNIList {
	if in == nil {
		return nil
	}
	out := new(TungstenCNIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TungstenCNIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TungstenCNISpec) DeepCopyInto(out *TungstenCNISpec) {
	*out = *in
	out.PodNetwork = in.PodNetwork
	out.ServiceNetwork = in.ServiceNetwork
	out.IpFabricNetwork = in.IpFabricNetwork
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TungstenCNISpec.
func (in *TungstenCNISpec) DeepCopy() *TungstenCNISpec {
	if in == nil {
		return nil
	}
	out := new(TungstenCNISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TungstenCNIStatus) DeepCopyInto(out *TungstenCNIStatus) {
	*out = *in
	if in.Controllers != nil {
		in, out := &in.Controllers, &out.Controllers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TungstenCNIStatus.
func (in *TungstenCNIStatus) DeepCopy() *TungstenCNIStatus {
	if in == nil {
		return nil
	}
	out := new(TungstenCNIStatus)
	in.DeepCopyInto(out)
	return out
}
