// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminSecretType) DeepCopyInto(out *AdminSecretType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminSecretType.
func (in *AdminSecretType) DeepCopy() *AdminSecretType {
	if in == nil {
		return nil
	}
	out := new(AdminSecretType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIConfigType) DeepCopyInto(out *CNIConfigType) {
	*out = *in
	out.PodNetwork = in.PodNetwork
	out.ServiceNetwork = in.ServiceNetwork
	out.IpFabricNetwork = in.IpFabricNetwork
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIConfigType.
func (in *CNIConfigType) DeepCopy() *CNIConfigType {
	if in == nil {
		return nil
	}
	out := new(CNIConfigType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatapathConfigType) DeepCopyInto(out *DatapathConfigType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatapathConfigType.
func (in *DatapathConfigType) DeepCopy() *DatapathConfigType {
	if in == nil {
		return nil
	}
	out := new(DatapathConfigType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpFabricNetworkType) DeepCopyInto(out *IpFabricNetworkType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpFabricNetworkType.
func (in *IpFabricNetworkType) DeepCopy() *IpFabricNetworkType {
	if in == nil {
		return nil
	}
	out := new(IpFabricNetworkType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodNetworkType) DeepCopyInto(out *PodNetworkType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodNetworkType.
func (in *PodNetworkType) DeepCopy() *PodNetworkType {
	if in == nil {
		return nil
	}
	out := new(PodNetworkType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDN) DeepCopyInto(out *SDN) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDN.
func (in *SDN) DeepCopy() *SDN {
	if in == nil {
		return nil
	}
	out := new(SDN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SDN) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDNList) DeepCopyInto(out *SDNList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SDN, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDNList.
func (in *SDNList) DeepCopy() *SDNList {
	if in == nil {
		return nil
	}
	out := new(SDNList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SDNList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDNSpec) DeepCopyInto(out *SDNSpec) {
	*out = *in
	out.AdminSecretRef = in.AdminSecretRef
	out.CNIConfig = in.CNIConfig
	out.DatapathConfig = in.DatapathConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDNSpec.
func (in *SDNSpec) DeepCopy() *SDNSpec {
	if in == nil {
		return nil
	}
	out := new(SDNSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDNStatus) DeepCopyInto(out *SDNStatus) {
	*out = *in
	if in.Controllers != nil {
		in, out := &in.Controllers, &out.Controllers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDNStatus.
func (in *SDNStatus) DeepCopy() *SDNStatus {
	if in == nil {
		return nil
	}
	out := new(SDNStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNetworkType) DeepCopyInto(out *ServiceNetworkType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNetworkType.
func (in *ServiceNetworkType) DeepCopy() *ServiceNetworkType {
	if in == nil {
		return nil
	}
	out := new(ServiceNetworkType)
	in.DeepCopyInto(out)
	return out
}
