apiVersion: v1
kind: ConfigMap
metadata:
  name: configzookeeperenv
  namespace: {{ .TF_NAMESPACE }}
data:
  ZOOKEEPER_NODES: {{ .CONFIGDB_NODES }}
  ZOOKEEPER_PORT: "{{ .ZOOKEEPER_PORT }}"
  ZOOKEEPER_PORTS: "{{ .ZOOKEEPER_PORTS }}"
