apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-manager-config
  namespace: kube-system
data:
  KUBERNETES_API_SERVER: {{ KUBERNETES_API_SERVER }}
  KUBERNETES_API_SECURE_PORT: "{{ KUBERNETES_API_SECURE_PORT }}"
  K8S_TOKEN_FILE: "/tmp/serviceaccount/token"

# Containers section
