apiVersion: v1
kind: Secret
metadata:
  name: tungsten-kube-manager-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: tungsten-kube-manager
type: kubernetes.io/service-account-token
