apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sdns.tungsten.atsgen.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.releaseTag
    name: Release
    type: string
  - JSONPath: .status.state
    name: State
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: tungsten.atsgen.com
  names:
    kind: SDN
    listKind: SDNList
    plural: sdns
    singular: sdn
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SDN is the Schema for the sdns API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Define the desired SDN deployment parameters
          properties:
            adminSecretRef:
              description: AdminSecretRef reference to secret holding password for
                Tungsten Fabric Controller admin, if not specified it fallsback to
                the default Admin Password
              properties:
                name:
                  description: Name reference to Oject secret
                  type: string
                namespace:
                  description: Namespace reference to Oject secret, if empty secret
                    is assumed to be available in operator namespace
                  type: string
              type: object
            cniConfig:
              description: CNIConfig supplies configuration used for Tungsten Fabric
                CNI
              properties:
                clusterName:
                  description: cluster name
                  type: string
                ipFabricNetwork:
                  description: ip fabric network parameters
                  properties:
                    cidr:
                      description: ip fabric network CIDR
                      type: string
                  type: object
                ipForwarding:
                  description: ip fabric forwarding, supported value enable, snat,
                    where as empty field means ip fabric forwarding disabled
                  enum:
                  - snat
                  - enable
                  type: string
                podNetwork:
                  description: pod network parameters
                  properties:
                    cidr:
                      description: pod network CIDR
                      type: string
                  type: object
                serviceNetwork:
                  description: service network parameters
                  properties:
                    cidr:
                      description: service network CIDR
                      type: string
                  type: object
                useHostNewtorkService:
                  description: use host network services
                  type: boolean
              type: object
            datapathConfig:
              description: DatapathConfig supplies configuration for Tungsten Fabric
                Datapath
              properties:
                useVrouter:
                  description: UseVrouter as datpath for CNI
                  type: boolean
              type: object
            releaseTag:
              description: ReleaseTag for the container images used empty release
                tag would assume automatically move to the latest image tag supported
              type: string
          type: object
        status:
          description: SDNStatus defines the observed state of SDN
          properties:
            controllers:
              items:
                type: string
              type: array
            error:
              type: string
            releaseTag:
              type: string
            stage:
              type: string
            state:
              description: state of deployment
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
