apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tungstencnis.tungsten.atsgen.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.releaseTag
    name: Release
    type: string
  - JSONPath: .status.state
    name: State
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: tungsten.atsgen.com
  names:
    kind: TungstenCNI
    listKind: TungstenCNIList
    plural: tungstencnis
    singular: tungstencni
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: TungstenCNI is the Schema for the tungstencnis API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Define the desired TungstenCNI deployment parameters
          properties:
            clusterName:
              description: cluster name
              type: string
            ipFabricNetwork:
              description: ip fabric network parameters
              properties:
                cidr:
                  description: ip fabric network CIDR
                  type: string
              type: object
            ipForwarding:
              description: ip fabric forwarding, supported value enable, snat, where
                as empty field means ip fabric forwarding disabled
              enum:
              - snat
              - enable
              type: string
            podNetwork:
              description: pod network parameters
              properties:
                cidr:
                  description: pod network CIDR
                  type: string
              type: object
            releaseTag:
              description: release tag for the container images used
              type: string
            serviceNetwork:
              description: service network parameters
              properties:
                cidr:
                  description: service network CIDR
                  type: string
              type: object
            useHostNewtorkService:
              description: use host network services
              type: boolean
            useVrouter:
              description: use vrouter as datpath for CNI
              type: boolean
          required:
          - releaseTag
          type: object
        status:
          description: TungstenCNIStatus defines the observed state of TungstenCNI
          properties:
            controllers:
              items:
                type: string
              type: array
            error:
              type: string
            releaseTag:
              type: string
            state:
              description: state of deployment
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
