kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tf-operator
subjects:
- kind: ServiceAccount
  name: tf-operator
  namespace: atsgen
roleRef:
  kind: ClusterRole
  name: tf-operator
  apiGroup: rbac.authorization.k8s.io
