apiVersion: v1
kind: ConfigMap
metadata:
  name: vrouter-config
  namespace: {{ .TF_NAMESPACE }}
data:
  DPDK_UIO_DRIVER: {{ .DPDK_UIO_DRIVER }}
  VROUTER_ENCRYPTION: "{{ .VROUTER_ENCRYPTION }}"
  VROUTER_GATEWAY: {{ .VROUTER_GATEWAY }}
