---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tungsten-kube-manager
  namespace: {{ .TF_NAMESPACE }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tungsten-kube-manager
  namespace: {{ .TF_NAMESPACE }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
# used to create network-attachment-definitions.k8s.cni.cncf.io
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tungsten-kube-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tungsten-kube-manager
subjects:
- kind: ServiceAccount
  name: tungsten-kube-manager
  namespace: {{ .TF_NAMESPACE }}
