apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tungsten-controller-webui
  namespace: {{ .TF_NAMESPACE }}
  labels:
    app: tungsten-controller-webui
spec:
  selector:
    matchLabels:
      app: tungsten-controller-webui
  template:
    metadata:
      labels:
        app: tungsten-controller-webui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.tungsten.io/webui"
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      initContainers:
      - name: tungsten-node-init
        image: "{{ .CONTAINER_REGISTRY }}/{{ .CONTAINER_PREFIX }}-node-init:{{ .CONTAINER_TAG }}"
        imagePullPolicy: ""
        securityContext:
          privileged: true
        env:
        - name: CONTRAIL_STATUS_IMAGE
          value: "{{ .CONTAINER_REGISTRY }}/{{ .CONTAINER_PREFIX }}-status:{{ .CONTAINER_TAG }}"
        envFrom:
        - configMapRef:
            name: env
        volumeMounts:
        - mountPath: /host/usr/bin
          name: host-usr-bin
      containers:
      - name: tungsten-controller-webui-job
        image: "{{ .CONTAINER_REGISTRY }}/{{ .CONTAINER_PREFIX }}-controller-webui-job:{{ .CONTAINER_TAG }}"
        imagePullPolicy: ""
        envFrom:
        - configMapRef:
            name: env
        volumeMounts:
        - mountPath: /var/log/contrail
          name: webui-logs
      - name: tungsten-controller-webui-web
        image: "{{ .CONTAINER_REGISTRY }}/{{ .CONTAINER_PREFIX }}-controller-webui-web:{{ .CONTAINER_TAG }}"
        imagePullPolicy: ""
        envFrom:
        - configMapRef:
            name: env
        volumeMounts:
        - mountPath: /var/log/contrail
          name: webui-logs
      imagePullSecrets:
      - name: {{ .TUNGSTEN_IMAGE_PULL_SECRET }}
      volumes:
      - name: webui-logs
        hostPath:
          path: /var/log/contrail/webui
      - name: host-usr-bin
        hostPath:
          path: /opt/tungsten/bin
