apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-manager-config
  namespace: {{ .TF_NAMESPACE }}
data:
  KUBERNETES_API_SERVER: {{ .KUBERNETES_API_SERVER }}
  KUBERNETES_API_SECURE_PORT: "{{ .KUBERNETES_API_SECURE_PORT }}"
  K8S_TOKEN_FILE: "/tmp/serviceaccount/token"
  KUBERNETES_CLUSTER_NAME: {{ .KUBERNETES_CLUSTER_NAME }}
  KUBERNETES_POD_SUBNETS: {{ .KUBERNETES_POD_SUBNETS }}
  KUBERNETES_SERVICE_SUBNETS: {{ .KUBERNETES_SERVICE_SUBNETS }}
  KUBERNETES_IP_FABRIC_SUBNETS: {{ .KUBERNETES_IP_FABRIC_SUBNETS }}
  KUBERNETES_IP_FABRIC_FORWARDING: "{{ .KUBERNETES_IP_FABRIC_FORWARDING }}"
  KUBERNETES_IP_FABRIC_SNAT: "{{ .KUBERNETES_IP_FABRIC_SNAT }}"
  KUBERNETES_HOST_NETWORK_SERVICE: "{{ .KUBERNETES_HOST_NETWORK_SERVICE }}"

# Containers section
